apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-redis
  template:
    metadata:
      labels:
        app: mini-redis
    spec:
      containers:
        - name: mini-redis
          image: mini-redis
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
